### ISSUE TITLE
QQSP Touchscreen Functionality post Klipper FW?

### ISSUE THREAD

**Issue by beebenutz** [CobraPi/Klipper-Firmware-FLSUN-QQ-S-Pro#25]
Is it normal for the QQSP touchscreen to only display "complete" after updating firmware to Klipper? 
Is this also the general outcome with all screens connected to the machine's micro-controller?
Just wandering if I have something configured incorrectly, and if I update my other machines, will the integrated screens on the other machine's also be non-functional?

It would be nice if the mcu screens could be utilized to al least show some stats or print progress or anything useful!

Thanks

**Comment by conlank** [comment]
These screens are not compatible with klipper.

**Comment by beebenutz** [comment]
> These screens are not compatible with klipper.

Thanks for the elaborate response.

**Comment by conlank** [comment]
I could explain why they are fundamentally incompatible, but googling the part name, looking at the manufacturers repo would be enlightening as if I told you that these screens are grbl controllers, i.e. send gcode over serial to the MCU, these screens have their own controller, basically think of them as an early version of the klipper pi.
